#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Working on your project before committing'

# Check linter
yarn lint-staged ||
(
    echo '❌👷🔨❌ lint-staged failed ❌👷🔨❌';
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
